<?php

namespace gypcms\filter;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../src/filter/Filter.php';
require_once dirname(__FILE__).'/../../../src/filter/BasicFilter.php';

/**
 * Test class for BasicFilter.
 * Generated by PHPUnit on 2010-03-01 at 18:36:15.
 */
class BasicFilterTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var BasicFilter
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new BasicFilter;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * Basic test
   */
  public function testProcess()
  {
    $this->assertEquals('Test <b>test</b>', $this->object->process('Test <b>test</b>'));
    $this->assertEquals('Test "&\'&" test', $this->object->process('Test "&\'&" test'));
  }
}
?>
