# Defines the data shown on the front page. In this case use the index page class and use the data in the data/index.yml file
default:
  url: /
  page: index
  data: index

# Defines a search result page
search:
  url: /search
  page: search
  data: ~

# Defines a list of all articles page sorted by publish date
all:
  url: /articles
  page: list
  sort:
    data: publish
    type: desc
  data: ~

# Defines a non-paginated list of the ten latest posts
paged:
  url: /latest
  page: list
  sort:
    data: publish
    type: desc
  limit:
    num: 10
    type: ~
  data: ~

# Defines a paginated list of the ten latest posts
paged:
  url: /archive
  page: list
  sort:
    data: publish
    type: desc
  limit:
    num: 10
    type: page
  data: ~

# Defines a rss stream of the 25 latest posts
rss:
  url: /rss
  page: rss
  sort:
    data: publish
    type: desc
  limit:
    num: 25
    type: ~
  data: ~
