settings:
  name: Gypcms example site
  logo: gfx/gypcms.gif
  author: Fredrik Wallgren
  language: en
  theme: natural-gloom
  cssFiles:
    fancybox:
      url: /js/lib/fancybox/jquery.fancybox-1.3.1.css
      media: screen
  javascriptFiles: [/js/lib/jquery/jquery-1.4.2.min.js, /js/lib/fancybox/jquery.fancybox-1.3.1.pack.js, /js/lib/jquery.easing/jquery.easing-1.3.js, /js/lib/jquery.mousewheel/jquery.mousewheel.min.js ]
  viewerclass: fancybox